# Generated by Django 5.0.1 on 2026-02-01 09:10

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('quiz_start', 'Quiz Started'), ('quiz_complete', 'Quiz Completed'), ('resource_view', 'Resource Viewed'), ('resource_download', 'Resource Downloaded'), ('news_view', 'News Viewed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_phone', models.CharField(blank=True, max_length=15)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('total_quizzes_taken', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_news', models.BooleanField(default=False)),
                ('can_edit_news', models.BooleanField(default=False)),
                ('can_delete_news', models.BooleanField(default=False)),
                ('can_upload_resources', models.BooleanField(default=False)),
                ('can_edit_resources', models.BooleanField(default=False)),
                ('can_delete_resources', models.BooleanField(default=False)),
                ('can_create_quizzes', models.BooleanField(default=False)),
                ('can_edit_quizzes', models.BooleanField(default=False)),
                ('can_delete_quizzes', models.BooleanField(default=False)),
                ('can_host_kahoot', models.BooleanField(default=False)),
                ('can_create_students', models.BooleanField(default=False)),
                ('can_manage_classes', models.BooleanField(default=False)),
                ('can_view_student_stats', models.BooleanField(default=False)),
                ('allowed_categories', models.JSONField(blank=True, default=list, help_text='List of category IDs this teacher can work with')),
                ('can_create_schools', models.BooleanField(default=False)),
                ('can_create_classes', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher Permission',
                'verbose_name_plural': 'Teacher Permissions',
                'db_table': 'teacher_permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('teacher', 'Teacher'), ('student', 'Student'), ('guest', 'Guest')], default='guest', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
