# Generated by Django 5.0.1 on 2026-02-01 09:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'db_table': 'news_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for previews', max_length=500)),
                ('content', models.TextField(help_text='Full content (supports Markdown/HTML)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('post_type', models.CharField(choices=[('news', 'News'), ('announcement', 'Announcement'), ('blog', 'Blog Post'), ('update', 'Update')], default='news', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='news.newscategory')),
            ],
            options={
                'db_table': 'news_posts',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.newscomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newspost')),
            ],
            options={
                'db_table': 'news_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar'])])),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.newspost')),
            ],
            options={
                'db_table': 'news_attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['-published_at', 'status'], name='news_posts_publish_51415e_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['author', '-published_at'], name='news_posts_author__0591f8_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['category', '-published_at'], name='news_posts_categor_86c9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['is_featured', '-published_at'], name='news_posts_is_feat_8fabbf_idx'),
        ),
        migrations.AddIndex(
            model_name='newscomment',
            index=models.Index(fields=['post', '-created_at'], name='news_commen_post_id_2acbf9_idx'),
        ),
        migrations.AddIndex(
            model_name='newscomment',
            index=models.Index(fields=['author', '-created_at'], name='news_commen_author__29e10a_idx'),
        ),
    ]
