# Generated by Django 5.0.1 on 2026-02-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags', null=True),
        ),
    ]
