# Generated by Django 5.0.1 on 2026-02-01 09:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short code for region', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('school_number', models.CharField(help_text='e.g., 41', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('principal_name', models.CharField(blank=True, max_length=200)),
                ('principal_phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_created', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='organizations.region')),
            ],
            options={
                'db_table': 'schools',
                'ordering': ['region', 'school_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 9-A, 11-B', max_length=100)),
                ('grade_level', models.IntegerField(choices=[(1, '1st Grade'), (2, '2nd Grade'), (3, '3rd Grade'), (4, '4th Grade'), (5, '5th Grade'), (6, '6th Grade'), (7, '7th Grade'), (8, '8th Grade'), (9, '9th Grade'), (10, '10th Grade'), (11, '11th Grade'), (12, '12th Grade')], validators=[django.core.validators.MinValueValidator(1)])),
                ('section', models.CharField(help_text='e.g., A, B, C', max_length=10)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('max_students', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='assigned_classes', to=settings.AUTH_USER_MODEL)),
                ('class_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='organizations.school')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'class_groups',
                'ordering': ['school', 'grade_level', 'section'],
            },
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_from', models.DateField(default=django.utils.timezone.now)),
                ('assigned_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='organizations.classgroup')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assignments', to='resources.category')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_class_assignments',
                'ordering': ['class_group', 'subject'],
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['code'], name='regions_code_aa1ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['is_active'], name='regions_is_acti_dadff5_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['region', 'school_number'], name='schools_region__0266e5_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active'], name='schools_is_acti_b64f0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('region', 'school_number')},
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['school', 'grade_level'], name='class_group_school__f84a59_idx'),
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['academic_year'], name='class_group_academi_f6f80b_idx'),
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['is_active'], name='class_group_is_acti_c3bfac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('school', 'grade_level', 'section', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='teacherclassassignment',
            index=models.Index(fields=['teacher', 'is_active'], name='teacher_cla_teacher_1fc1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherclassassignment',
            index=models.Index(fields=['class_group', 'is_active'], name='teacher_cla_class_g_154f0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherclassassignment',
            unique_together={('teacher', 'class_group', 'subject')},
        ),
    ]
