# Generated by Django 5.0.1 on 2026-02-01 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('quizzes_attempted', models.IntegerField(default=0)),
                ('quizzes_completed', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('resources_viewed', models.IntegerField(default=0)),
                ('resources_downloaded', models.IntegerField(default=0)),
                ('kahoot_rooms_created', models.IntegerField(default=0)),
                ('kahoot_participants', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Activity',
                'verbose_name_plural': 'Daily Activities',
                'db_table': 'daily_activity',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClassStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('total_quizzes_attempted', models.IntegerField(default=0)),
                ('total_quizzes_completed', models.IntegerField(default=0)),
                ('average_class_score', models.FloatField(default=0.0)),
                ('average_streak', models.FloatField(default=0.0)),
                ('total_active_days', models.IntegerField(default=0)),
                ('top_student_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('class_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='organizations.classgroup')),
                ('top_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Statistics',
                'verbose_name_plural': 'Class Statistics',
                'db_table': 'class_statistics',
            },
        ),
        migrations.CreateModel(
            name='QuizStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('median_score', models.FloatField(default=0.0)),
                ('highest_score', models.FloatField(default=0.0)),
                ('lowest_score', models.FloatField(default=0.0)),
                ('pass_rate', models.FloatField(default=0.0)),
                ('total_passed', models.IntegerField(default=0)),
                ('average_time', models.IntegerField(default=0, help_text='Average seconds to complete')),
                ('fastest_time', models.IntegerField(default=0)),
                ('slowest_time', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('easiest_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quizzes.question')),
                ('hardest_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quizzes.question')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_statistics', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Statistics',
                'verbose_name_plural': 'Quiz Statistics',
                'db_table': 'quiz_statistics',
            },
        ),
        migrations.CreateModel(
            name='CategoryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizzes_attempted', models.IntegerField(default=0)),
                ('quizzes_completed', models.IntegerField(default=0)),
                ('quizzes_passed', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('highest_score', models.FloatField(default=0.0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('resources_viewed', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics', to='resources.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Statistics',
                'verbose_name_plural': 'Category Statistics',
                'db_table': 'category_statistics',
                'indexes': [models.Index(fields=['user', 'category'], name='category_st_user_id_3e935d_idx'), models.Index(fields=['category', '-average_score'], name='category_st_categor_7cf004_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('global', 'Global'), ('category', 'Category'), ('class', 'Class'), ('school', 'School'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('rankings', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='resources.category')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='organizations.classgroup')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='organizations.school')),
            ],
            options={
                'db_table': 'leaderboards',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['leaderboard_type', '-last_updated'], name='leaderboard_leaderb_c70824_idx'), models.Index(fields=['category', '-last_updated'], name='leaderboard_categor_94226e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quizzes_attempted', models.IntegerField(default=0)),
                ('total_quizzes_completed', models.IntegerField(default=0)),
                ('total_quizzes_passed', models.IntegerField(default=0)),
                ('average_score_percentage', models.FloatField(default=0.0)),
                ('highest_score_percentage', models.FloatField(default=0.0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total seconds spent on quizzes')),
                ('average_quiz_time', models.IntegerField(default=0, help_text='Average seconds per quiz')),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('global_rank', models.IntegerField(blank=True, null=True)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('school_rank', models.IntegerField(blank=True, null=True)),
                ('total_resources_viewed', models.IntegerField(default=0)),
                ('total_resources_downloaded', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
                'db_table': 'user_statistics',
                'indexes': [models.Index(fields=['-average_score_percentage'], name='user_statis_average_e02533_idx'), models.Index(fields=['-total_points_earned'], name='user_statis_total_p_094d1c_idx'), models.Index(fields=['global_rank'], name='user_statis_global__e89f88_idx')],
            },
        ),
    ]
