from rest_framework.test import APITestCase
from django.contrib.auth import get_user_model

from news.models import NewsPost

User = get_user_model()


class NewsPostModelTest(APITestCase):
    def setUp(self):
        self.author = User.objects.create_user(
            username='news_author', password='pw12345', role='teacher',
        )

    def test_slug_is_autogenerated_from_title(self):
        post = NewsPost.objects.create(
            title='Hello World', content='body', author=self.author, status='published',
        )
        self.assertEqual(post.slug, 'hello-world')

    def test_published_at_set_when_published(self):
        post = NewsPost.objects.create(
            title='Goes Live', content='body', author=self.author, status='published',
        )
        self.assertIsNotNone(post.published_at)

    def test_draft_has_no_published_at(self):
        post = NewsPost.objects.create(
            title='Still A Draft', content='body', author=self.author, status='draft',
        )
        self.assertIsNone(post.published_at)


class NewsPostVisibilityTest(APITestCase):
    def setUp(self):
        self.author = User.objects.create_user(
            username='news_author2', password='pw12345', role='teacher',
        )
        NewsPost.objects.create(
            title='Live Post', content='hi', author=self.author, status='published',
        )
        NewsPost.objects.create(
            title='Hidden Draft', content='wip', author=self.author, status='draft',
        )

    def test_anonymous_sees_only_published_posts(self):
        res = self.client.get('/api/news/posts/')
        self.assertEqual(res.status_code, 200)
        titles = [p['title'] for p in res.data['results']]
        self.assertIn('Live Post', titles)
        self.assertNotIn('Hidden Draft', titles)
