# Generated by Django 5.0.1 on 2026-02-01 09:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quizzes/questions/%Y/%m/')),
                ('question_type', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('true_false', 'True/False')], default='single', max_length=20)),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quizzes/options/%Y/%m/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.question')),
            ],
            options={
                'db_table': 'quiz_question_options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quiz_type', models.CharField(choices=[('standard', 'Standard Quiz'), ('kahoot', 'Kahoot-Style')], default='standard', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='medium', max_length=20)),
                ('timing_mode', models.CharField(choices=[('per_question', 'Time per Question'), ('total', 'Total Time for Quiz'), ('none', 'No Time Limit')], default='per_question', max_length=20)),
                ('time_per_question', models.IntegerField(default=30, help_text='Seconds per question', validators=[django.core.validators.MinValueValidator(5)])),
                ('total_time', models.IntegerField(default=900, help_text='Total seconds for entire quiz', validators=[django.core.validators.MinValueValidator(60)])),
                ('passing_score', models.FloatField(default=60.0, help_text='Minimum percentage to pass', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Show correct answers after completion')),
                ('randomize_questions', models.BooleanField(default=False, help_text='Randomize question order')),
                ('randomize_options', models.BooleanField(default=False, help_text='Randomize answer options')),
                ('allow_review', models.BooleanField(default=True, help_text='Allow users to review answers before submitting')),
                ('max_attempts', models.IntegerField(default=0, help_text='0 = unlimited attempts')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('requires_login', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='quizzes/thumbnails/%Y/%m/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('total_attempts', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='resources.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='KahootRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('max_players', models.IntegerField(default=50)),
                ('allow_late_join', models.BooleanField(default=True)),
                ('host', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'superuser']}, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(limit_choices_to={'quiz_type': 'kahoot'}, on_delete=django.db.models.deletion.CASCADE, related_name='kahoot_rooms', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'kahoot_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.IntegerField(default=0, help_text='Time taken in seconds')),
                ('score', models.IntegerField(default=0, help_text='Total points earned')),
                ('max_score', models.IntegerField(default=0, help_text='Maximum possible points')),
                ('score_percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kahoot_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='quizzes.kahootroom')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(default=0, help_text='Time taken to answer in seconds')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizzes.question')),
                ('selected_options', models.ManyToManyField(related_name='user_selections', to='quizzes.questionoption')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
            ],
            options={
                'db_table': 'quiz_answers',
                'ordering': ['attempt', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='KahootLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('average_time', models.FloatField(default=0.0, help_text='Average time per question')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kahoot_rankings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='quizzes.kahootroom')),
            ],
            options={
                'db_table': 'kahoot_leaderboard',
                'ordering': ['room', 'rank'],
                'indexes': [models.Index(fields=['room', 'rank'], name='kahoot_lead_room_id_d83373_idx')],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'order'], name='quiz_questi_questio_755c59_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['category', '-created_at'], name='quizzes_categor_88935c_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_type', 'is_published'], name='quizzes_quiz_ty_1d887c_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_by', '-created_at'], name='quizzes_created_6ecd6d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='quiz_questi_quiz_id_76bc24_idx'),
        ),
        migrations.AddIndex(
            model_name='kahootroom',
            index=models.Index(fields=['room_code'], name='kahoot_room_room_co_25edd0_idx'),
        ),
        migrations.AddIndex(
            model_name='kahootroom',
            index=models.Index(fields=['status', '-created_at'], name='kahoot_room_status_b8e463_idx'),
        ),
        migrations.AddIndex(
            model_name='kahootroom',
            index=models.Index(fields=['host', '-created_at'], name='kahoot_room_host_id_dc9459_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-started_at'], name='quiz_attemp_user_id_69a804_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', '-started_at'], name='quiz_attemp_quiz_id_2dc7ae_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status', '-started_at'], name='quiz_attemp_status_058b21_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['kahoot_room', '-score'], name='quiz_attemp_kahoot__b33e83_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['attempt', 'question'], name='quiz_answer_attempt_b8a4a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
