# Generated by Django 5.0.1 on 2026-02-01 09:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='resources.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'resource_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('description', models.TextField(help_text='Resource description')),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('post', 'Article/Post'), ('link', 'External Link'), ('document', 'Document'), ('presentation', 'Presentation')], max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='resources/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'avi', 'mov'])])),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or other video URL')),
                ('video_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt'])])),
                ('content', models.TextField(blank=True, help_text='Full content for posts/articles (supports Markdown/HTML)')),
                ('external_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, help_text='Original source', max_length=300)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('access_level', models.CharField(choices=[('public', 'Public - All users'), ('students', 'Students only'), ('registered', 'Registered users only'), ('premium', 'Premium/Paid')], default='public', max_length=20)),
                ('allow_download', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.category')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="User's personal notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collections/covers/')),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_collections', to=settings.AUTH_USER_MODEL)),
                ('resources', models.ManyToManyField(blank=True, related_name='collections', to='resources.resource')),
            ],
            options={
                'db_table': 'resource_collections',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5')),
                ('review', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='resource_ca_slug_06b175_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='resource_ca_parent__bce373_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category', '-created_at'], name='resources_categor_ecb727_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', '-created_at'], name='resources_resourc_f9b8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_published', '-created_at'], name='resources_is_publ_07eefc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='resources_uploade_85cbde_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcebookmark',
            index=models.Index(fields=['user', '-created_at'], name='resource_bo_user_id_2d9bdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcebookmark',
            unique_together={('user', 'resource')},
        ),
        migrations.AddIndex(
            model_name='resourcerating',
            index=models.Index(fields=['resource', '-rating'], name='resource_ra_resourc_28a2da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcerating',
            unique_together={('user', 'resource')},
        ),
    ]
