# Generated by Django 5.0.1 on 2026-02-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Short description for previews', max_length=500),
        ),
    ]
