from rest_framework.test import APITestCase
from django.contrib.auth import get_user_model

from resources.models import Resource, Category

User = get_user_model()


def make_resource(category, uploader, title, slug, published):
    return Resource.objects.create(
        title=title,
        slug=slug,
        description='desc',
        resource_type='link',
        external_url='https://example.com',
        category=category,
        uploaded_by=uploader,
        is_published=published,
    )


class CategoryModelTest(APITestCase):
    def test_slug_is_autogenerated_from_name(self):
        category = Category.objects.create(name='Study Materials')
        self.assertEqual(category.slug, 'study-materials')


class ResourceVisibilityTest(APITestCase):
    def setUp(self):
        self.uploader = User.objects.create_user(
            username='uploader', password='pw12345', role='teacher',
        )
        self.category = Category.objects.create(name='Library')
        make_resource(self.category, self.uploader, 'Public Doc', 'public-doc', True)
        make_resource(self.category, self.uploader, 'Hidden Doc', 'hidden-doc', False)

    def test_anonymous_sees_only_published_resources(self):
        res = self.client.get('/api/resources/')
        self.assertEqual(res.status_code, 200)
        titles = [r['title'] for r in res.data['results']]
        self.assertIn('Public Doc', titles)
        self.assertNotIn('Hidden Doc', titles)
